#
# Configuration file only for development
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spacecontroller_e?useSSL=false
    username: root
    password: backbase
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect