#
# Configuration file only for development
#

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tar_e?useSSL=false
    username: root
    password: backbase
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com:
      backbase:
        cxp:
          targeting: INFO

