#
# Configuration file only for development
#

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rendition_e?useSSL=false
    username: root
    password: backbase
    driver-class-name: com.mysql.jdbc.Driver